# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'iOSExampleAppM2020-2018' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for iOSExampleAppM2020-2018
  		pod 'OAuthSwift', '~> 1.2.0'

  target 'iOSExampleAppM2020-2018Tests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'iOSExampleAppM2020-2018UITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
